### PR TITLE
Halve framerate and dimension if they are big

### LINKED ISSUE #28: File size and frame rate defaults
To avoid creating huge/wasteful GIFs, I suggest having smart defaults.

* If resolution is >= 640px wide, halve it. Videos have chroma subsampling and compression artefacts that are wasteful in GIF, so halving resolution for GIF is a good idea anyway.
* If framerate is >= 24fps, halve it. Frames cost a lot in GIF.

### PR DESCRIPTION
**Pull request by LarsJK**
We already clamp the framerate to 5-30. Do wee need to also halve it? If so should the halving be based on the clamped value, or the original value then clamped to 5-30..?

closes #28

### CODE REVIEW

**Comment by LarsJK** [comment]
Maybe its better if we instead of halving, used 24 fps and 640 width as standard if the video is bigger..?

**Comment by kornelski** [comment]
I'd suggest halve first, then cap. Halving (or dividing by integer in general) gives the best quality -- smoothest animation and nicest scaling.

GIF can only express framerates as 100/n, and most screens can play only 60/n, so 10 and 20fps are the best framerates for GIF. 

Uneven framerate scaling causes judder: https://en.wikipedia.org/wiki/Three-two_pull_down

**Comment by sindresorhus** [comment]
@LarsJK Are you still interested in finishing this? No worries if you don't have time right now.

**Comment by LarsJK** [comment]
@sindresorhus Yeah I can finish this.
Do you have any suggestions for the scale slider? See #28 and @kornelski 's comment on [#25](https://github.com/sindresorhus/gifski-app/issues/25#issuecomment-373951951)

I tried implementing a ticked slider but it it didn't look very good. Too many ticks and probably need to do something about the styling to make it work better with the dark background.

**Comment by sindresorhus** [comment]
My idea is that we use a normal slider, but have a list of predefined sizes, like commented in https://github.com/sindresorhus/gifski-app/issues/25#issuecomment-373951951. So let's say if we had 4 predefined sizes, when the slider is at 0%, it would pick the first, when it's at 20% it would still pick the first, when at 26% it would pick the second, and when at 76% it would pick the last element. So we just spread the elements evenly out. So it's like a tick slider without the ticks.

**Comment by sindresorhus** [comment]
I also think we should revert the open/save dialog to be non-dark. It looked cool at first, but it's clearly not designed to be dark and there are a lot of weird visual bugs.

**Comment by sindresorhus** [comment]
We could also maybe make the text on the right-side of the slider a text field instead, for the perfectionists that want an exact size more easily.

**Comment by LarsJK** [comment]
>I also think we should revert the open/save dialog to be non-dark. It looked cool at first, but it's clearly not designed to be dark and there are a lot of weird visual bugs.

@sindresorhus 🤞Real dark mode support announce next week

**Comment by sindresorhus** [comment]
> 🤞Real dark mode support announce next week

We got it!!!!!!! Note my change in https://github.com/sindresorhus/gifski-app/commit/28948889a8a544c731db9cd29cec98423882da3f

**Comment by sindresorhus** [comment]
> I also think we should revert the open/save dialog to be non-dark. It looked cool at first, but it's clearly not designed to be dark and there are a lot of weird visual bugs.

Done in https://github.com/sindresorhus/gifski-app/commit/28948889a8a544c731db9cd29cec98423882da3f

**Comment by LarsJK** [comment]
@sindresorhus I simplified the code a bit, and changed the minimum scale so that it will allow you to scale the GIF down to 10x10 independent of the input size..

I'm struggling to find a good way to use predefined size and a slider. Do you prefer a slider or could we do a dropdown like preview:

preview

The preset that give the best quality (1/n scaling) can be marked with "best quality" or something like that..

Maybe we should merge this to get better defaults and figure out the way to handle predefines in another PR?

**Comment by sindresorhus** [comment]
> Maybe we should merge this to get better defaults and figure out the way to handle predefines in another PR?

👍 Can you open an issue about the remaining things we need to change? Like slider=>dropdown.

**Comment by sindresorhus** [comment]
This looks great :)

**Pull request merged**
