### PR TITLE
Update gifski

### PR DESCRIPTION
**Pull request by kornelski**
#34

### CODE REVIEW

**Comment by sindresorhus** [comment]
It now builds again with this PR, but I'm getting a crash at the end of converting a video to GIF:

```
Thread 1: Fatal error: Failed to write to output, with underlying error: A one-time function was called twice, or functions were called in wrong order
```

**Comment by kornelski** [comment]
I've added better error reporting to the write call

**Comment by sindresorhus** [comment]
That fixed the crash 👌

**Comment by sindresorhus** [comment]
Not important, but I'm getting a warning about:

```
warning: unused manifest key: package.autobins
```

Any way to silence it?

**Comment by kornelski** [comment]
`package.autobins` is needed for forward compatibility with the next version of Rust (one of them will warn in the transition period, ugh).

**Comment by kornelski** [comment]
From what I could find it's because the linker thinks it needs to support C++ exceptions.

Adding "`-Wl,-no_compact_unwind`" flag (somewhere…) should help.

**Comment by sindresorhus** [comment]
> Adding "-Wl,-no_compact_unwind" flag (somewhere…) should help.

Yeah, I found that too, but couldn't figure out where to add it.

**Pull request merged**
