### PR TITLE
Fudge openmp from homebrew's GCC 7.2

### PR DESCRIPTION
**Pull request by kornelski**
This should make it noticeably faster. However, it's a bit hacky since it needs to link with GCC's library, which brew puts wherever it wants. Maybe it could be improved with injection of `brew --prefix` somewhere in the config.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@kornelski Can you rebase from master and fix the merge conflict?

**Comment by sindresorhus** [comment]
I tested this PR against release build of master, and it decreases the convert time by ~25%:

```
openmp release build 14.65 seconds
master release build 19.61 seconds
```

**Comment by sindresorhus** [comment]
@kornelski You said we could not use GCD as the frames have to be converted in order, I'm then curious how OpenMP is able to achieve this speed improvement. Do you know?

**Comment by kornelski** [comment]
OpenMP affects internals of libimagequant, e.g. remapping of pixels is done in parallel. It's more fine-grained parallelism than what GCD aims for.

**Comment by sindresorhus** [comment]
Do all frames depend on each other? For example, could we split the a video into two videos, process them in parallel, and then merge them at the end?

**Comment by sindresorhus** [comment]
Could also encode intraframes in parallel.

This is a good read if you haven’t read it already: http://www.drdobbs.com/parallel/optimizing-video-encoding-using-threads/225600370

**Comment by kornelski** [comment]
In GIFs produced by gifski every frame depends on its previous frame, by design. It's equivalent to a video without keyframes. Encoding of frames themselves is already very parallelized.

Splitting input video into parts (roughly equal to number of cores), encoding parts independently and then stitching together would parallelize GIF creation quite well at cost of adding keyframe-like frames in the GIF that may have lower quality (since they won't be able to correctly reuse background from their previous frame).

I've also considered encoding video in fragments, stitching fragments, and then re-encoding frames on the stitches to reduce quality loss. 

However, all of this considerably increases complexity.

**Pull request merged**
