### PR TITLE
Link OpenMP runtime statically

### LINKED ISSUE #11: Master crashes
@kornelski When I "archive" master and run the app, it crashes if I don't have `gcc` installed (try with `brew uninstall gcc`).

```
Process:               Gifski [11129]
Path:                  /Applications/Gifski.app/Contents/MacOS/Gifski
Identifier:            com.sindresorhus.Gifski
Version:               1.1.0 (2)
App Item ID:           0
App External ID:       0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Gifski [11129]
User ID:               502

Date/Time:             2018-02-25 13:12:05.364 -0800
OS Version:            Mac OS X 10.13.2 (17C89)
Report Version:        12
Anonymous UUID:        23501669-5784-1A67-4D38-0583AC23BEC6

Sleep/Wake UUID:       7463A5D6-0414-4382-9426-082B4CE27497

Time Awake Since Boot: 630000 seconds
Time Since Wake:       280 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /Applications/Gifski.app/Contents/MacOS/Gifski
  Reason: image not found

Binary Images:
       0x104d7d000 -        0x104ec3ff7 +com.sindresorhus.Gifski (1.1.0 - 2) <F81B6CB9-1DAC-37D0-9569-408389989AD8> /Applications/Gifski.app/Contents/MacOS/Gifski
       0x104f0e000 -        0x104f2eff7 +ProgressKit (1.0 - ???) <5845D54C-644D-309D-857B-F5F266CCE798> /Applications/Gifski.app/Contents/Frameworks/ProgressKit.framework/Versions/A/ProgressKit
       0x10decf000 -        0x10df1998f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff69c21000 -     0x7fff69c3dffb  libresolv.9.dylib (65) <E8F3415B-4472-3202-8901-41FD87981DB2> /usr/lib/libresolv.9.dylib
```

Why is it trying to load the dynamic library of `libgomp`?

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #11

### CODE REVIEW

**Comment by sindresorhus** [comment]
This still crashes without GCC installed:

```
Process:               Gifski [79276]
Path:                  /Users/USER/Downloads/*/Gifski.app/Contents/MacOS/Gifski
Identifier:            com.sindresorhus.Gifski
Version:               1.1.0 (2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Gifski [79276]
User ID:               501

Date/Time:             2018-02-26 18:03:59.093 +0700
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Anonymous UUID:        E1F234A7-B61B-954B-2FF5-D9E0D1A6E14C

Sleep/Wake UUID:       54060D0C-8602-4893-B9DA-16241D515D58

Time Awake Since Boot: 65000 seconds
Time Since Wake:       19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /Users/USER/Downloads/*/Gifski.app/Contents/MacOS/Gifski
  Reason: image not found

Binary Images:
       0x100a36000 -        0x100b9dff7 +com.sindresorhus.Gifski (1.1.0 - 2) <4D8F4D04-728E-32BD-B4CA-412426D495A8> /Users/USER/Downloads/*/Gifski.app/Contents/MacOS/Gifski
       0x100bec000 -        0x100c0cff7 +ProgressKit (1.0 - ???) <5845D54C-644D-309D-857B-F5F266CCE798> /Users/USER/Downloads/*/Gifski.app/Contents/Frameworks/ProgressKit.framework/Versions/A/ProgressKit
       0x10239c000 -        0x1023e698f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff67758000 -     0x7fff67774ffb  libresolv.9.dylib (65) <E8F3415B-4472-3202-8901-41FD87981DB2> /usr/lib/libresolv.9.dylib
```

**Comment by sindresorhus** [comment]
And I see some warnings when building, but it might be nothing:

```
ld: warning: could not create compact unwind for __Unwind_RaiseException: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_ForcedUnwind: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume: does not use RBP or RSP based frame
ld: warning: could not create compact unwind for __Unwind_Resume_or_Rethrow: does not use RBP or RSP based frame
```

**Comment by sindresorhus** [comment]
Have you seen https://stackoverflow.com/a/39843038/64949 ? Seems like it would be possible to use `clang` when installed from Homebrew.

**Comment by kornelski** [comment]
I don't expect custom clang build to solve the OpenMP runtime problem. The problem here is caused during linking, and Xcode already uses Apple's clang to link.

OpenMP needs a runtime library, and there are two versions of that library. The problem here is that Xcode/clang's `ld` is not smart enough/too clever to select the version suitable for redistributable applications.

**Comment by kornelski** [comment]
Another option could be to switch from `libgifski.a` back to `libgifski.dylib` (and ensure it's packaged properly in the way Xcode's archiving and App Store will accept it), because that moves responsibility for linking OpenMP to Cargo, and I've already configured it to do it properly.

**Comment by sindresorhus** [comment]
I see. We can try what you have here first, and consider the dynamic option if we encounter more problems.

**Pull request merged**
